title: Molecular Dynamics - Sao Carlos Physics Institute (MD-SCPI)
description: Evaluation of the unbinding kinetics of Mineralocorticoid (MR) receptor steroid agonist Cortisol (COL) and Aldosterone (AS4) ligands.
author: Sebastian Aguilera Novoa


show_downloads: true
theme: jekyll-theme-leap-day

markdown: kramdown

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
